version: '3.8'
services:
  db:
    container_name: recipes_db
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server
  web:
    container_name: recipes_web
    build: .
    command: /bin/sh -c "rm -f ./tmp/pids/server.pid && bundle i && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RECIPES_DATABASE_HOST: db
      REDIS_URL: redis://redis:6379/0
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 3000:3000
    volumes:
      - .:/web
      - /web/vendor
      - /web/node_modules
    links:
      - db
      - elasticsearch
      - mailcatcher
    stdin_open: true
    tty: true
    depends_on:
      - db
  sidekiq:
    container_name: recipes_sidekiq
    build: .
    command:  /bin/sh -c "bundle i && bundle exec sidekiq"
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/web
      - /web/node_modules
    links:
      - redis
      - db
      - mailcatcher
  elasticsearch:
    container_name: elasticsearch
    image: bitnami/elasticsearch:latest
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - /elasticsearch/data
  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'
volumes:
  db-data:
    driver: local
